// <auto-generated />
using System;
using CoWorkHub.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoWorkHub.Services.Migrations
{
    [DbContext(typeof(_210095Context))]
    [Migration("20260208171024_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoWorkHub.Services.Database.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityLogId")
                        .HasName("PK__Activity__19A9B7AFC7A107AA");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CityId")
                        .HasName("PK__City__F2D21B7654331DD4");

                    b.HasIndex("CountryId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CountryId")
                        .HasName("PK__Country__10D1609F585C5019");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.PasswordResetRequest", b =>
                {
                    b.Property<int>("PasswordResetRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasswordResetRequestId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PasswordResetRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("StateMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPaymentAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A38168D4919");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1D3A568E9C3");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PeopleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SpaceUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StateMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("SpaceUnitId");

                    b.HasIndex("UsersId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Resource", b =>
                {
                    b.Property<int>("ResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourcesId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourcesId")
                        .HasName("PK__Resource__EE325BD4A75B7880");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Review", b =>
                {
                    b.Property<int>("ReviewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewsId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingSpacesId")
                        .HasColumnType("int");

                    b.HasKey("ReviewsId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("WorkingSpacesId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Role", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolesId")
                        .HasName("PK__Roles__C4B27840A7A06CDF");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnit", b =>
                {
                    b.Property<int>("SpaceUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceUnitId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("StateMachine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkingSpaceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("int");

                    b.HasKey("SpaceUnitId");

                    b.HasIndex("WorkingSpaceId");

                    b.HasIndex("WorkspaceTypeId");

                    b.ToTable("SpaceUnits");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnitImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SpaceUnitId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("SpaceUnitId");

                    b.ToTable("SpaceUnitImages");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnitResource", b =>
                {
                    b.Property<int>("SpaceResourcesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceResourcesId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.Property<int>("SpaceUnitId")
                        .HasColumnType("int");

                    b.HasKey("SpaceResourcesId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ResourcesId");

                    b.HasIndex("SpaceUnitId");

                    b.ToTable("SpaceUnitResources");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.User", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsersId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsersId")
                        .HasName("PK__Users__A349B062A2433C41");

                    b.HasIndex("CityId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E44DEE34AB")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AEE1B60D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkingSpace", b =>
                {
                    b.Property<int>("WorkingSpacesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkingSpacesId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkingSpacesId")
                        .HasName("PK__WorkingS__A2EB71C9F9A3BC23");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("WorkingSpaces");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkingSpaceImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("WorkingSpacesId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__WorkingS__7516F70C380ADEDB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkingSpacesId");

                    b.ToTable("WorkingSpaceImages");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkspaceType", b =>
                {
                    b.Property<int>("WorkspaceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkspaceTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkspaceTypeId")
                        .HasName("PK__Workspac__39CF5B8191065C67");

                    b.ToTable("WorkspaceType", (string)null);
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.ActivityLog", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ActivityLog_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.City", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_City_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.PasswordResetRequest", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Payment", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_PaymentMethod");

                    b.HasOne("CoWorkHub.Services.Database.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Payments");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Reservation", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.SpaceUnit", "SpaceUnit")
                        .WithMany("Reservations")
                        .HasForeignKey("SpaceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnit_Reservations");

                    b.HasOne("CoWorkHub.Services.Database.User", "Users")
                        .WithMany("Reservations")
                        .HasForeignKey("UsersId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservation_Users");

                    b.Navigation("SpaceUnit");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Review", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.User", "DeletedByNavigation")
                        .WithMany("ReviewDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK_Review_DeletedBy");

                    b.HasOne("CoWorkHub.Services.Database.Reservation", "Reservation")
                        .WithOne("Review")
                        .HasForeignKey("CoWorkHub.Services.Database.Review", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoWorkHub.Services.Database.WorkingSpace", null)
                        .WithMany("Reviews")
                        .HasForeignKey("WorkingSpacesId");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnit", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.WorkingSpace", "WorkingSpace")
                        .WithMany("SpaceUnits")
                        .HasForeignKey("WorkingSpaceId")
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnit_WorkingSpace");

                    b.HasOne("CoWorkHub.Services.Database.WorkspaceType", "WorkspaceType")
                        .WithMany("SpaceUnits")
                        .HasForeignKey("WorkspaceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnit_WorkspaceType");

                    b.Navigation("WorkingSpace");

                    b.Navigation("WorkspaceType");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnitImage", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.SpaceUnit", "SpaceUnit")
                        .WithMany("SpaceUnitImages")
                        .HasForeignKey("SpaceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnitImage_SpaceUnit");

                    b.Navigation("SpaceUnit");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnitResource", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.User", "CreatedByNavigation")
                        .WithMany("SpaceUnitResourceCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnitResource_CreatedBy");

                    b.HasOne("CoWorkHub.Services.Database.User", "DeletedByNavigation")
                        .WithMany("SpaceUnitResourceDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK_SpaceUnitResource_DeletedBy");

                    b.HasOne("CoWorkHub.Services.Database.User", "ModifiedByNavigation")
                        .WithMany("SpaceUnitResourceModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_SpaceUnitResource_ModifiedBy");

                    b.HasOne("CoWorkHub.Services.Database.Resource", "Resources")
                        .WithMany("SpaceUnitResources")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnitResource_Resource");

                    b.HasOne("CoWorkHub.Services.Database.SpaceUnit", "SpaceUnit")
                        .WithMany("SpaceUnitResources")
                        .HasForeignKey("SpaceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpaceUnitResource_SpaceUnit");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Resources");

                    b.Navigation("SpaceUnit");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.User", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_City");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.UserRole", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("CoWorkHub.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkingSpace", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.City", "City")
                        .WithMany("WorkingSpaces")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkingSpaces_City");

                    b.HasOne("CoWorkHub.Services.Database.User", "CreatedByNavigation")
                        .WithMany("WorkingSpaceCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_WorkingSpacesCreatedBy_Users");

                    b.HasOne("CoWorkHub.Services.Database.User", "DeletedByNavigation")
                        .WithMany("WorkingSpaceDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("FK_WorkingSpacesDeletedBy_Users");

                    b.HasOne("CoWorkHub.Services.Database.User", "ModifiedByNavigation")
                        .WithMany("WorkingSpaceModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_WorkingSpacesModifiedBy_Users");

                    b.Navigation("City");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkingSpaceImage", b =>
                {
                    b.HasOne("CoWorkHub.Services.Database.User", "CreatedByNavigation")
                        .WithMany("WorkingSpaceImages")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_WorkingSpaceImagesCreatedBy_Users");

                    b.HasOne("CoWorkHub.Services.Database.WorkingSpace", "WorkingSpaces")
                        .WithMany("WorkingSpaceImages")
                        .HasForeignKey("WorkingSpacesId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkingSpaceImages_WorkingSpaces");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("WorkingSpaces");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.City", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkingSpaces");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Resource", b =>
                {
                    b.Navigation("SpaceUnitResources");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.SpaceUnit", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("SpaceUnitImages");

                    b.Navigation("SpaceUnitResources");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Reservations");

                    b.Navigation("ReviewDeletedByNavigations");

                    b.Navigation("SpaceUnitResourceCreatedByNavigations");

                    b.Navigation("SpaceUnitResourceDeletedByNavigations");

                    b.Navigation("SpaceUnitResourceModifiedByNavigations");

                    b.Navigation("UserRoles");

                    b.Navigation("WorkingSpaceCreatedByNavigations");

                    b.Navigation("WorkingSpaceDeletedByNavigations");

                    b.Navigation("WorkingSpaceImages");

                    b.Navigation("WorkingSpaceModifiedByNavigations");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkingSpace", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SpaceUnits");

                    b.Navigation("WorkingSpaceImages");
                });

            modelBuilder.Entity("CoWorkHub.Services.Database.WorkspaceType", b =>
                {
                    b.Navigation("SpaceUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
